export const navigation: Record<string, [string, string, string][]> = {
  farmer: [
    ["dashboard", "Dashboard", "डैशबोर्ड"],
    ["profile", "My Profile & Crops", "प्रोफ़ाइल और फसलें"],
    ["prices", "Market Prices", "मंडी भाव"],
    ["lots", "My Lots", "मेरी उपज"],
    ["bids", "Buyer Offers", "खरीदार की बोलियाँ"],
    ["circles", "Harvest Circles", "हार्वेस्ट सर्कल"],
    ["quality", "Quality Check", "गुणवत्ता जाँच"],
    ["warehouse", "Warehouse", "गोदाम"],
    ["transactions", "Transactions", "लेन-देन"],
    ["transport", "Transport", "परिवहन"],
    ["assistant", "AI Assistant", "कृषि सहायक"],
    ["schemes", "Government Schemes", "सरकारी योजनाएँ"],
    ["messages", "Messages", "संदेश"],
    ["notifications", "Notifications", "सूचनाएँ"],
    ["disputes", "Disputes", "विवाद"],
  ],
  fpo: [
    ["dashboard", "Dashboard", "डैशबोर्ड"],
    ["farmers", "Farmers", "किसान"],
    ["lots", "Produce & Lots", "उपज और लॉट"],
    ["quality", "Quality Verification", "गुणवत्ता सत्यापन"],
    ["circles", "Harvest Circles", "हार्वेस्ट सर्कल"],
    ["collection", "Collection Hub", "संग्रह केंद्र"],
    ["warehouse", "Warehouse", "गोदाम"],
    ["inventory", "Inventory", "भंडार"],
    ["demand", "Buyer Demand", "खरीदार माँग"],
    ["transport", "Transport", "परिवहन"],
    ["transactions", "Transactions", "लेन-देन"],
    ["messages", "Messages", "संदेश"],
    ["notifications", "Notifications", "सूचनाएँ"],
    ["reports", "Reports & Analytics", "रिपोर्ट और विश्लेषण"],
  ],
  buyer: [
    ["dashboard", "Dashboard", "डैशबोर्ड"],
    ["profile", "Profile & Verification", "प्रोफ़ाइल और सत्यापन"],
    ["demand", "Buyer Demand", "खरीदार माँग"],
    ["lots", "Find Lots", "उपज खोजें"],
    ["circles", "Harvest Circles", "हार्वेस्ट सर्कल"],
    ["bids", "My Bids", "मेरी बोलियाँ"],
    ["transactions", "Transactions", "लेन-देन"],
    ["transport", "Transport", "परिवहन"],
    ["messages", "Messages", "संदेश"],
    ["notifications", "Notifications", "सूचनाएँ"],
    ["disputes", "Disputes", "विवाद"],
  ],
  transporter: [
    ["dashboard", "Dashboard", "डैशबोर्ड"],
    ["profile", "Profile & Verification", "प्रोफ़ाइल और सत्यापन"],
    ["vehicles", "Vehicles", "वाहन"],
    ["transport", "Available Jobs", "उपलब्ध काम"],
    ["jobs", "My Jobs", "मेरे काम"],
    ["earnings", "Earnings", "कमाई"],
    ["messages", "Messages", "संदेश"],
    ["notifications", "Notifications", "सूचनाएँ"],
  ],
  admin: [
    ["dashboard", "Overview", "अवलोकन"],
    ["users", "Users & Verification", "उपयोगकर्ता और सत्यापन"],
    ["staff", "FPO Staff Permissions", "FPO कर्मचारी अनुमति"],
    ["lots", "Lots & Bids", "उपज और बोलियाँ"],
    ["demand", "Buyer Demand", "खरीदार माँग"],
    ["circles", "FPOs & Circles", "FPO और सर्कल"],
    ["quality", "Quality", "गुणवत्ता"],
    ["warehouse", "Warehouses & Inventory", "गोदाम और भंडार"],
    ["transport", "Transport", "परिवहन"],
    ["transactions", "Payments & Settlements", "भुगतान और निपटान"],
    ["schemes", "Schemes", "योजनाएँ"],
    ["imports", "CSV Imports", "CSV आयात"],
    ["models", "AI & Models", "AI और मॉडल"],
    ["disputes", "Disputes", "विवाद"],
    ["reported", "Reported Messages", "रिपोर्ट किए गए संदेश"],
    ["notifications", "Notifications", "सूचनाएँ"],
    ["reports", "Reports", "रिपोर्ट"],
    ["audit", "Audit", "ऑडिट"],
    ["settings", "Settings", "सेटिंग्स"],
  ],
};
