ALTER TABLE "Lot" ADD CONSTRAINT "lot_quantity_positive" CHECK ("kg" > 0 AND "reservedKg" >= 0 AND "reservedKg" <= "kg");
ALTER TABLE "Lot" ADD CONSTRAINT "lot_rate_positive" CHECK ("expectedRate" > 0);
ALTER TABLE "Bid" ADD CONSTRAINT "bid_rate_positive" CHECK ("rate" > 0 AND ("costPaise" IS NULL OR "costPaise" >= 0));
ALTER TABLE "Warehouse" ADD CONSTRAINT "warehouse_capacity_positive" CHECK ("capacityKg" > 0 AND "ratePaise" >= 0);
ALTER TABLE "Booking" ADD CONSTRAINT "booking_quantity_dates" CHECK ("kg" > 0 AND "startDate" < "endDate");
ALTER TABLE "Contribution" ADD CONSTRAINT "contribution_weights" CHECK ("pledgedKg" > 0 AND "receivedKg" >= 0 AND "acceptedKg" >= 0 AND "acceptedKg" <= "receivedKg" AND "receivedKg" <= "pledgedKg");
ALTER TABLE "PaymentOrder" ADD CONSTRAINT "payment_amount_positive" CHECK ("amountPaise" > 0);
ALTER TABLE "Circle" ADD CONSTRAINT "circle_weights" CHECK ("targetKg" > 0 AND "minimumKg" > 0 AND "minimumKg" <= "targetKg");
ALTER TABLE "Session" ADD FOREIGN KEY ("userId") REFERENCES "User"("id");
ALTER TABLE "Lot" ADD FOREIGN KEY ("ownerId") REFERENCES "User"("id");
ALTER TABLE "Bid" ADD FOREIGN KEY ("buyerId") REFERENCES "User"("id");
ALTER TABLE "Agreement" ADD FOREIGN KEY ("bidId") REFERENCES "Bid"("id");
ALTER TABLE "Agreement" ADD FOREIGN KEY ("sellerId") REFERENCES "User"("id");
ALTER TABLE "Agreement" ADD FOREIGN KEY ("buyerId") REFERENCES "User"("id");
ALTER TABLE "Demand" ADD FOREIGN KEY ("buyerId") REFERENCES "User"("id");
ALTER TABLE "Circle" ADD FOREIGN KEY ("fpoId") REFERENCES "User"("id");
ALTER TABLE "Circle" ADD FOREIGN KEY ("demandId") REFERENCES "Demand"("id");
ALTER TABLE "Contribution" ADD FOREIGN KEY ("circleId") REFERENCES "Circle"("id");
ALTER TABLE "Contribution" ADD FOREIGN KEY ("farmerId") REFERENCES "User"("id");
ALTER TABLE "Contribution" ADD FOREIGN KEY ("lotId") REFERENCES "Lot"("id");
ALTER TABLE "Booking" ADD FOREIGN KEY ("warehouseId") REFERENCES "Warehouse"("id");
ALTER TABLE "Booking" ADD FOREIGN KEY ("farmerId") REFERENCES "User"("id");
ALTER TABLE "TransportJob" ADD FOREIGN KEY ("agreementId") REFERENCES "Agreement"("id");
ALTER TABLE "TransportJob" ADD FOREIGN KEY ("transporterId") REFERENCES "User"("id");
ALTER TABLE "TransportJob" ADD FOREIGN KEY ("vehicleId") REFERENCES "Vehicle"("id");
ALTER TABLE "Quote" ADD FOREIGN KEY ("jobId") REFERENCES "TransportJob"("id");
ALTER TABLE "Quote" ADD FOREIGN KEY ("vehicleId") REFERENCES "Vehicle"("id");
ALTER TABLE "PaymentOrder" ADD FOREIGN KEY ("agreementId") REFERENCES "Agreement"("id");
ALTER TABLE "ProviderEvent" ADD FOREIGN KEY ("orderId") REFERENCES "PaymentOrder"("id");
ALTER TABLE "LedgerEntry" ADD FOREIGN KEY ("agreementId") REFERENCES "Agreement"("id");
ALTER TABLE "Allocation" ADD FOREIGN KEY ("agreementId") REFERENCES "Agreement"("id");
ALTER TABLE "Allocation" ADD FOREIGN KEY ("farmerId") REFERENCES "User"("id");
ALTER TABLE "Message" ADD FOREIGN KEY ("threadId") REFERENCES "Thread"("id");
ALTER TABLE "Message" ADD FOREIGN KEY ("senderId") REFERENCES "User"("id");
ALTER TABLE "Notification" ADD FOREIGN KEY ("userId") REFERENCES "User"("id");
ALTER TABLE "Dispute" ADD FOREIGN KEY ("agreementId") REFERENCES "Agreement"("id");
CREATE INDEX "agreement_seller" ON "Agreement"("sellerId");
CREATE INDEX "agreement_buyer" ON "Agreement"("buyerId");
CREATE INDEX "booking_overlap" ON "Booking"("warehouseId","startDate","endDate");
CREATE INDEX "message_thread_date" ON "Message"("threadId","createdAt");
CREATE INDEX "notification_user" ON "Notification"("userId","read");
CREATE INDEX "outbox_due" ON "Outbox"("status","availableAt");

